### ISSUE TITLE
Having issues..

### ISSUE THREAD

**Issue by davidm71** [pbatard/uefi-simple#10]
Hi Pete,

I have VS 2015 installed and used the git console to clone the project but running into a few roadblocks. 1. VS says project out of date. 2. When i try to compile it VS errs and says missing v141 project tools. How can i fix this?

Thanks

**Comment by pbatard** [comment]
Hi David,

uefi-simple requires VS2017. There is no compatibility or support being offered for VS2015. If you want to use any other compiler than the ones that are mentioned in the README, I'm afraid that you are on your own.

**Comment by davidm71** [comment]
Thank you. I'll upgrade I guess. Thanks.
