### ISSUE TITLE
Can not use any C function

### ISSUE THREAD

**Issue by gomidas** [pbatard/uefi-simple#12]
Hello, thank you for providing this project. That was really helpful. However, I got an interesting issue. I debug project . I write efi code but I can not use any of C library function. I get errors. Something like unresolved external... What is the reason of that ?

**Comment by yw662** [comment]
These functions are not there for free, they are implemented by "standard library", or libc. You need a libc implementation if you want them.

**Comment by gomidas** [comment]
> You need a libc implementation if you want them.

Where can I get libc ? Then got "glibc-2.32". Will I put this inside project or somewhere then will I add this frop project properties->additional include directories ?

**Comment by yw662** [comment]
Not glibc, at least not the one implemented for linux. Libc is platform specific, you need the libc for UEFI. There is a libc implementation in tianocore.
