### ISSUE TITLE
uefi-simple & QEMU Issue

### ISSUE THREAD

**Issue by donkharrison** [pbatard/uefi-simple#2]
I tried to follow the instructions on your blog: "Easily create UEFI applications using Visual Studio 2013."  This was very useful, and I am able to create applications but I am not able to get the emulator to work under a windows environment.  In your text, you give the link to the QEMU site, but there are no binaries at the download link anymore.  I found where the old link pointed to (http://www.h7.dion.ne.jp/~qemu-win/) and tried those binaries.  I had to edit the debug.vbs file to point to "Programs (x86)" and also the .exe filename.  I'm still not sure I did that right.  In any event, I could not get it to work properly.  I downloaded some more recent binaries from here: http://qemu.weilnetz.de/w64/, and I get further, but when QEMU opens, I get the "Guest has not initialized the display (yet)." message. If I try running QEMU from the command line: 

C:\uefi-simple>"C:\Program Files\qemu\qemu-system-x86_64w.exe" -L . -bios OVMF_x86_64.fd -net none -hda fat:image     

I get the same thing.

Any advice you might have would be greatly appreciated.
-Don

**Comment by sar3th** [comment]
Hi Don,
I have encountered the same problem. I've found [qemu-w64-setup-20150424](http://qemu.weilnetz.de/w64/qemu-w64-setup-20150424.exe) from http://qemu.weilnetz.de/w64/ works fine. Seems to be a qemu-problem...
Regards,
sar3th

**Comment by pbatard** [comment]
>  I had to edit the debug.vbs file to point to "Programs (x86)" and also the .exe filename.

As mentioned in the blog post: _"You should download and install QEMU, preferably the 64 bit version, and preferably to its default of C:\Program Files\qemu."_. Of course, if you don't install the 64-bit version, then you may have to change some things.

Unfortunately, QEMU does not provide official Windows binaries, so I can't really help with the installation process as there is no official way to do it. Please try with the binaries @sar3th mentioned, and if that still doesn't work, feel free to reopen the issue.
