### ISSUE TITLE
how to use assembly in UEFI:SIMPLE with vs?

### ISSUE THREAD

**Issue by zszszsz** [pbatard/uefi-simple#3]
While this may not be an issue but it will be really helpful since vs doesn't support inline assembly with x64 compiler

**Comment by pbatard** [comment]
Sorry. I wish I had the time to look into that, but I really don't. :sob: 

You will have to figure out how to use assembly yourself... Have you tried asking Visual Studio or UEFI forums? They should have a better idea of what you can try.
