### ISSUE TITLE
Launch debug from Visual Studio but nothing happens

### ISSUE THREAD

**Issue by mibsi** [pbatard/uefi-simple#6]
I followed your guide on the blog but I'm not able to see anything when launching Debug from Visual Studio 2015.
I can see VS in debug mode and qemu process between active processes but no interface.
I doublechecked everything but the result is the same.
Also if I try to launch qemu from the command line I have the same issue.
I'm working on windows 10 with visual studio 2015, no compilation error.
Thank you

**Comment by pbatard** [comment]
It's probably your `qemu` installation then, especially as you indicate that you have the same issue when launching `qemu` manually. Did you install the QEMU 64-bit binaries referenced in the README (the ones from [here](https://qemu.weilnetz.de/w64/))?

**Comment by mibsi** [comment]
Yes I did

**Comment by pbatard** [comment]
And you're sure you are running Windows 10 64-bit?
Also, are you sure you compiled the x86 version and not the ARM?
And did you get a prompt for the `OVMF.fd` download? Do you see and `OVMF_<ARCH>.fd` in your root directory?

**Comment by mibsi** [comment]
I ' m sure about 64 bit version of Windows.
I tried both ia32 and x64 configuration but the result was the same.
I got that prompt and I had OVMF_<ARCH>.fd in my directory

**Comment by pbatard** [comment]
Should be `OVMF_X64.fd` or `OVMF_IA32.fd`. If that's not the case then that's an issue.
If you have either of those, then you need to figure out why you can't seem to run `qemu` on your machine, as it's not an uefi-simple issue.

Try to run the following from your uefi-simple directory:

```
"C:\Program Files\qemu\qemu-system-x86_64w.exe" -L . -bios OVMF_X64.fd
```

(be careful that there **must** be a space between `-L` and `.`)
If that doesn't work, you'll have to sort the issue with the QEMU people.

**Comment by mibsi** [comment]
I've just tried (I saw the guide on OVMF page) and nothing happens...
I launched the command from the directory where i have the fd file. I had no errors but nothing happens :\

**Comment by pbatard** [comment]
I'm afraid the issue is on your side then. That has nothing to do with uefi-simple, so you'll need to sort it out on your own. Sorry.

**Comment by mibsi** [comment]
Yes i figured out it can be some kind of problem with qemu binaries, but Ii thought you could have some good news for me :)
Thank you anyway

**Comment by mibsi** [comment]
I resolved installing a previous version of binaries...just to let you know :)

**Comment by pbatard** [comment]
Okay.

**Comment by zszszsz** [comment]
it seems that there is sth. changed with the newer version of qemu? or maybe it is a broken installation?

**Comment by mibsi** [comment]
I don't know, Ii don't think it's a broken installation.
I simply downloaded the latest version from the site provided by the author and it doesn't work. With a previous one it works.

**Comment by pbatard** [comment]
Well, the problem is that the `qemu` people do not provide official Windows binaries, so the ones I am linking to are **unofficial**, which are provided "AS IS" and probably don't receive the same level of testing they would if they were official binaries. Therefore I'm not entirely surprised that some of these binaries might simply not work.

It actually says right so on the download site:

> QEMU for Windows is experimental software and might contain even serious bugs, so use the binaries at your own risk.

I think, if you can demonstrate the issue in a reproducible manner, you should contact the author of these binaries to let them know.
