### ISSUE TITLE
Broken on QEMU 2.9.0 Windows x64

### ISSUE THREAD

**Issue by keithdennison** [pbatard/uefi-simple#8]
Thank you for this project.

It does not work for me on Windows x64 with QEMU 2.9.0. It does work with 2.8.0. Probably not an issue in this project, but figured I would mention it in case someone else is having issues with the latest QEMU.

**Comment by pbatard** [comment]
Yeah, the latest QEMU builds for Windows seem to be broken and I'm kind of waiting so see if there's gonna be a 2.9.1 released, that fixes this.

I'll keep this issue opened to raise awareness about this issue.
