### ISSUE TITLE
debug.vbs 

### ISSUE THREAD

**Issue by jjolig** [pbatard/uefi-simple#9]
In my case I had to add the rw permission for the virtual hdd at the end of the debug.vbs.

`Call shell.Run("""" & QEMU_PATH & QEMU_EXE & """ " & QEMU_OPTS & " -L . -bios " & FW_FILE & " -hda fat:rw:image", 1, True)`

Without the permission the debug.vbs couldn't start the qemu.exe.

**Comment by pbatard** [comment]
A-Ha!

Thanks you so much for figuring the issue that has been plaguing users (see #8) trying to use this project with QEMU 2.9 on Windows.

From what I can see, it appears that the newer versions of QEMU insist on saving the firmware non-volatile variables to the ESP partition if it exists, so it wants to create an `NvVars` file there... which of course it can only do if the partition is mounted `rw`.

I really can't thank you enough for the tip. This has been an annoyance for a few of my projects that use QEMU on Windows, and, at long last, it can now be addressed.

I'll apply this fix right away!
